// ── Types ─────────────────────────────────────────────────────────────────────
// Designed for future Famly / YouTube / social integration.
// isPublic: false items are never rendered in the public gallery.

export type ContentType   = "photo" | "video" | "update";
export type BranchFilter  = "all" | "harrow" | "pinner" | "borehamwood";
export type CategoryFilter = "all" | "classroom" | "outdoor" | "events" | "learning";

export interface GalleryItem {
  id:          string;
  type:        ContentType;
  title:       string;
  description?: string;
  branch:      Exclude<BranchFilter,  "all">;
  category:    Exclude<CategoryFilter, "all">;
  date:        string;       // ISO "YYYY-MM-DD"
  featured:    boolean;
  source:      "famly" | "youtube" | "manual";
  isPublic:    boolean;
  // photos
  src?:         string;
  alt?:         string;
  aspectRatio?: number;      // height / width — drives masonry visual weight
  // videos
  youtubeId?:   string;
  thumbnailSrc?: string;
  duration?:    string;
  // updates
  excerpt?: string;
  href?:    string;
}

// ── Mock data ─────────────────────────────────────────────────────────────────
// Replace these arrays with API calls once Famly / YouTube are integrated.

export const GALLERY_ITEMS: GalleryItem[] = [
  // ── Photos ─────────────────────────────────────────────────────────────────
  // Each branch has 5 photo items so the branch-filter chip is never empty.
  // All `src` paths point at optimised assets in /public/home/branches/.

  // Harrow (5)
  {
    id: "p-h1",
    type: "photo",
    title: "Story-time prepared environment",
    description: "Little Red Riding Hood storytelling set on the Montessori work table.",
    branch: "harrow",
    category: "classroom",
    date: "2026-04-10",
    featured: true,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-01.webp",
    alt: "Storytelling table with Little Red Riding Hood books and Montessori letter cards at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h2",
    type: "photo",
    title: "Little Ducks water play",
    description: "Toddler-friendly water table activity.",
    branch: "harrow",
    category: "learning",
    date: "2026-04-08",
    featured: true,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-02.webp",
    alt: "Toddler at the Little Ducks water-play table at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h3",
    type: "photo",
    title: "Citrus sensory tray",
    description: "Hands-on discovery with citrus, water, and natural materials.",
    branch: "harrow",
    category: "learning",
    date: "2026-04-02",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-03.webp",
    alt: "Teacher and toddler exploring a citrus water sensory tray at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h4",
    type: "photo",
    title: "Outdoor garden",
    description: "Wisteria-shaded garden and outdoor learning area.",
    branch: "harrow",
    category: "outdoor",
    date: "2026-03-25",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-preview-01.webp",
    alt: "Children playing in the wisteria-shaded garden at Blue Nest Harrow",
    aspectRatio: 0.67,
  },
  {
    id: "p-h5",
    type: "photo",
    title: "Fizzy volcano experiment",
    description: "STEM curiosity through a hands-on chemistry experiment.",
    branch: "harrow",
    category: "events",
    date: "2026-03-15",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-05.webp",
    alt: "Three children running a fizzy volcano experiment at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h6",
    type: "photo",
    title: "Balance frames",
    description: "Practical-life balance frames help young children develop core stability.",
    branch: "harrow",
    category: "learning",
    date: "2026-03-10",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-04.webp",
    alt: "Child walking on Montessori balance frames at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h7",
    type: "photo",
    title: "Little Red Riding Hood reading",
    description: "Calm one-to-one storytelling with a Blue Nest teacher.",
    branch: "harrow",
    category: "classroom",
    date: "2026-03-05",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-06.webp",
    alt: "Blue Nest Harrow teacher reading Little Red Riding Hood with a child",
    aspectRatio: 0.75,
  },
  {
    id: "p-h8",
    type: "photo",
    title: "Outdoor sensory tray",
    description: "Natural materials, water and texture exploration outdoors.",
    branch: "harrow",
    category: "outdoor",
    date: "2026-02-28",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-07.webp",
    alt: "Child focused on an outdoor wood-and-water sensory tray at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h9",
    type: "photo",
    title: "Music sessions",
    description: "Weekly enrichment music programme.",
    branch: "harrow",
    category: "events",
    date: "2026-02-25",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-09.webp",
    alt: "Child playing a drum kit during a music session at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h10",
    type: "photo",
    title: "Imaginative role-play",
    description: "Ice-cream parlour role-play builds early social skills.",
    branch: "harrow",
    category: "classroom",
    date: "2026-02-20",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-10.webp",
    alt: "Children at the ice-cream parlour role-play area at Blue Nest Harrow",
    aspectRatio: 0.75,
  },

  // Harrow — 2026-06 refresh (14 new photos)
  {
    id: "p-h11", type: "photo", title: "Outdoor activities", description: "Children gathered around an outdoor activity table in the garden.",
    branch: "harrow", category: "outdoor", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-11.webp",
    alt: "Children gathered around an outdoor activity table in the Blue Nest Harrow garden",
    aspectRatio: 0.75,
  },
  {
    id: "p-h12", type: "photo", title: "Our garden", description: "The outdoor play area with slide, climbing toys and pergola.",
    branch: "harrow", category: "outdoor", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-12.webp",
    alt: "The outdoor play area with a slide, climbing toys and pergola at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h13", type: "photo", title: "Creative craft", description: "Exploring colourful dough and craft materials.",
    branch: "harrow", category: "learning", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-13.webp",
    alt: "Children exploring colourful dough and craft materials at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h14", type: "photo", title: "Small-world play", description: "A colourful small-world village set up for imaginative play.",
    branch: "harrow", category: "learning", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-14.webp",
    alt: "A colourful small-world village and animal display set up for imaginative play at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h15", type: "photo", title: "Guided learning", description: "An educator guiding two children through a tabletop activity.",
    branch: "harrow", category: "learning", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-15.webp",
    alt: "An educator guiding two children through a tabletop Montessori activity at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h16", type: "photo", title: "Working together", description: "An educator supporting a small group at the activity table.",
    branch: "harrow", category: "classroom", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-16.webp",
    alt: "An educator supporting a small group at the activity table at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h17", type: "photo", title: "Our classroom", description: "Children busy at activity tables across the bright classroom.",
    branch: "harrow", category: "classroom", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-17.webp",
    alt: "Children busy at activity tables across the bright Montessori classroom at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h18", type: "photo", title: "Hands-on making", description: "A child and educator working closely on a craft activity.",
    branch: "harrow", category: "learning", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-18.webp",
    alt: "Close-up of a child and educator working on a craft activity at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h19", type: "photo", title: "Fine-motor focus", description: "A toddler concentrating on a colourful threading activity.",
    branch: "harrow", category: "learning", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-19.webp",
    alt: "Toddler concentrating on a colourful threading activity at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h20", type: "photo", title: "Mealtimes together", description: "Children sharing a group snack-time table.",
    branch: "harrow", category: "classroom", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-20.webp",
    alt: "Children together at a group snack-time table at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h21", type: "photo", title: "ICT lessons", description: "Children using laptops during an ICT session.",
    branch: "harrow", category: "learning", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-21.webp",
    alt: "Children using laptops during an ICT session at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h22", type: "photo", title: "Circle time", description: "Children gathered for group circle time.",
    branch: "harrow", category: "classroom", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-22.webp",
    alt: "Children gathered for group circle time at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h23", type: "photo", title: "Early literacy", description: "Building words on a letter board with an educator.",
    branch: "harrow", category: "learning", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-23.webp",
    alt: "A child building words on a letter board with an educator at Blue Nest Harrow",
    aspectRatio: 0.75,
  },
  {
    id: "p-h24", type: "photo", title: "Prepared environment", description: "A well-prepared classroom with natural materials and open shelves.",
    branch: "harrow", category: "classroom", date: "2026-05-01", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/harrow/harrow-gallery-24.webp",
    alt: "A well-prepared Montessori classroom with natural materials and open shelves at Blue Nest Harrow",
    aspectRatio: 0.75,
  },

  // Pinner (5)
  {
    id: "p-p1",
    type: "photo",
    title: "Real-food preparation",
    description: "Children practising independence at the Montessori food-prep table.",
    branch: "pinner",
    category: "learning",
    date: "2026-04-12",
    featured: true,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-01.webp",
    alt: "Children at a Montessori real-food prep table with the Pink Tower at Blue Nest Pinner",
    aspectRatio: 0.75,
  },
  {
    id: "p-p2",
    type: "photo",
    title: "Outdoor mini-village",
    description: "Imaginative play in the Pinner garden.",
    branch: "pinner",
    category: "outdoor",
    date: "2026-04-05",
    featured: true,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-hero.webp",
    alt: "Children playing with a wooden village in the Blue Nest Pinner garden",
    aspectRatio: 0.67,
  },
  {
    id: "p-p3",
    type: "photo",
    title: "Practical-life dough activity",
    description: "Fine motor skills through play-doh impression work.",
    branch: "pinner",
    category: "classroom",
    date: "2026-03-28",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-03.webp",
    alt: "Teacher and three children at a practical-life dough activity at Blue Nest Pinner",
    aspectRatio: 0.75,
  },
  {
    id: "p-p4",
    type: "photo",
    title: "Reading nook",
    description: "Cosy reading corner with animal cushions.",
    branch: "pinner",
    category: "classroom",
    date: "2026-03-20",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-04.webp",
    alt: "Cosy reading nook with animal cushions at Blue Nest Pinner",
    aspectRatio: 0.75,
  },
  {
    id: "p-p5",
    type: "photo",
    title: "One-to-one Montessori work",
    description: "A teacher supporting a child through a Montessori puzzle.",
    branch: "pinner",
    category: "learning",
    date: "2026-03-15",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-05.webp",
    alt: "Teacher working one-to-one with a child on a Montessori puzzle at Blue Nest Pinner",
    aspectRatio: 0.75,
  },
  {
    id: "p-p6",
    type: "photo",
    title: "Independent stations",
    description: "Children working at their own pace at independent learning stations.",
    branch: "pinner",
    category: "classroom",
    date: "2026-03-08",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-06.webp",
    alt: "A busy Montessori classroom with children at independent learning stations at Blue Nest Pinner",
    aspectRatio: 0.67,
  },
  {
    id: "p-p7",
    type: "photo",
    title: "Quiet reading corner",
    description: "A calm space for stories and picture books.",
    branch: "pinner",
    category: "classroom",
    date: "2026-03-01",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-07.webp",
    alt: "Reading corner with picture-book caddy at Blue Nest Pinner",
    aspectRatio: 0.75,
  },
  {
    id: "p-p8",
    type: "photo",
    title: "Outdoor mini-village",
    description: "Imaginative play with a wooden village setup in the garden.",
    branch: "pinner",
    category: "outdoor",
    date: "2026-02-22",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-02.webp",
    alt: "Outdoor miniature village and farm animal models in the Blue Nest Pinner garden",
    aspectRatio: 0.67,
  },
  {
    id: "p-p9",
    type: "photo",
    title: "Welcoming our youngest learners",
    description: "Gentle one-to-one welcome at the dollhouse.",
    branch: "pinner",
    category: "classroom",
    date: "2026-02-15",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-welcome.webp",
    alt: "Teacher and child exploring a Montessori dollhouse activity at Blue Nest Pinner",
    aspectRatio: 0.75,
  },
  {
    id: "p-p10",
    type: "photo",
    title: "Wide classroom view",
    description: "Spacious, light-filled Montessori environment at Pinner.",
    branch: "pinner",
    category: "classroom",
    date: "2026-02-10",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/pinner/pinner-office.webp",
    alt: "Wide view of a busy Montessori classroom at Blue Nest Pinner",
    aspectRatio: 0.67,
  },

  // Pinner — 2026-06 refresh (14 new photos)
  {
    id: "p-p11", type: "photo", title: "Nature craft", description: "A nature and flower craft table in the garden.",
    branch: "pinner", category: "outdoor", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-08.webp",
    alt: "Children exploring a nature and flower craft table in the Blue Nest Pinner garden", aspectRatio: 0.75,
  },
  {
    id: "p-p12", type: "photo", title: "Guided learning", description: "An educator guiding an outdoor table activity.",
    branch: "pinner", category: "learning", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-09.webp",
    alt: "An educator guiding children through an activity at an outdoor table at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p13", type: "photo", title: "Creative craft", description: "A busy craft table with an educator.",
    branch: "pinner", category: "learning", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-10.webp",
    alt: "Children and an educator at a busy craft table at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p14", type: "photo", title: "Tabletop learning", description: "Children at a tabletop learning activity.",
    branch: "pinner", category: "learning", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-11.webp",
    alt: "Children working at a tabletop learning activity at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p15", type: "photo", title: "Water & sand play", description: "Outdoor water and sand play.",
    branch: "pinner", category: "outdoor", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-12.webp",
    alt: "Children at outdoor water and sand play at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p16", type: "photo", title: "Working together", description: "An educator with children at the activity table.",
    branch: "pinner", category: "classroom", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-13.webp",
    alt: "An educator with children gathered at the activity table at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p17", type: "photo", title: "Water play", description: "Children around the outdoor water-play table.",
    branch: "pinner", category: "outdoor", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-14.webp",
    alt: "Children gathered around the outdoor water-play table at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p18", type: "photo", title: "Our garden", description: "Children playing in the leafy garden.",
    branch: "pinner", category: "outdoor", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-15.webp",
    alt: "Children playing in the leafy outdoor garden at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p19", type: "photo", title: "Outdoor play", description: "Group play on the mat outdoors.",
    branch: "pinner", category: "outdoor", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-16.webp",
    alt: "Children gathered on a mat for outdoor group play at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p20", type: "photo", title: "Small-world play", description: "Building and exploring with toys on the mat.",
    branch: "pinner", category: "learning", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-17.webp",
    alt: "Children building and exploring with toys on the play mat at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p21", type: "photo", title: "Sensory water play", description: "An educator supporting a child at the water table.",
    branch: "pinner", category: "outdoor", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-18.webp",
    alt: "An educator supporting a child at the water-play table at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p22", type: "photo", title: "Outdoor exploration", description: "Exploring the garden with a bucket.",
    branch: "pinner", category: "outdoor", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-19.webp",
    alt: "A child exploring the garden with a bucket at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p23", type: "photo", title: "Mud kitchen", description: "The outdoor Mud Cafe mud-kitchen station.",
    branch: "pinner", category: "outdoor", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-20.webp",
    alt: "Children at the outdoor Mud Cafe mud-kitchen station at Blue Nest Pinner", aspectRatio: 0.75,
  },
  {
    id: "p-p24", type: "photo", title: "Focused discovery", description: "A child concentrating on a hands-on activity.",
    branch: "pinner", category: "learning", date: "2026-05-28", featured: false, source: "manual", isPublic: true,
    src: "/home/branches/pinner/pinner-gallery-21.webp",
    alt: "A child concentrating on a hands-on activity at Blue Nest Pinner", aspectRatio: 0.75,
  },

  // Borehamwood (5)
  {
    id: "p-b1",
    type: "photo",
    title: "Babies in the reading arch",
    description: "Two babies in the wooden reading arch with fairy lights.",
    branch: "borehamwood",
    category: "classroom",
    date: "2026-04-10",
    featured: true,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-04.webp",
    alt: "Two babies in the wooden reading arch with fairy lights at Blue Nest Borehamwood",
    aspectRatio: 0.75,
  },
  {
    id: "p-b2",
    type: "photo",
    title: "Outdoor learning playground",
    description: "Pergola, sand pit, climbing frame and balance bridges.",
    branch: "borehamwood",
    category: "outdoor",
    date: "2026-04-02",
    featured: true,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-hero.webp",
    alt: "Outdoor learning playground under the pergola at Blue Nest Borehamwood",
    aspectRatio: 0.67,
  },
  {
    id: "p-b3",
    type: "photo",
    title: "Cultural discovery — Africa bin",
    description: "Sensory exploration of cultures, animals, and geography.",
    branch: "borehamwood",
    category: "learning",
    date: "2026-03-22",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-08.webp",
    alt: "Africa-themed cultural sensory bin with globe and figurines at Blue Nest Borehamwood",
    aspectRatio: 0.75,
  },
  {
    id: "p-b4",
    type: "photo",
    title: "Spring reading area",
    description: "Cherry-blossom reading area with picture books.",
    branch: "borehamwood",
    category: "classroom",
    date: "2026-03-18",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-09.webp",
    alt: "Spring reading area with pink cherry-blossom tree at Blue Nest Borehamwood",
    aspectRatio: 0.75,
  },
  {
    id: "p-b5",
    type: "photo",
    title: "Mud kitchen",
    description: "Hands-on outdoor cooking and pretend play.",
    branch: "borehamwood",
    category: "outdoor",
    date: "2026-03-10",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-05.webp",
    alt: "Outdoor mud kitchen with chalkboard menu at Blue Nest Borehamwood",
    aspectRatio: 0.75,
  },
  {
    id: "p-b6",
    type: "photo",
    title: "Red Montessori cubes",
    description: "Building with the Red Knobless Cylinders at Borehamwood.",
    branch: "borehamwood",
    category: "learning",
    date: "2026-03-08",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-01.webp",
    alt: "Teacher with two children building with red Montessori cubes at Blue Nest Borehamwood",
    aspectRatio: 0.75,
  },
  {
    id: "p-b7",
    type: "photo",
    title: "Imagination corner",
    description: "Wisteria-and-foliage reading nook with story-time cushions.",
    branch: "borehamwood",
    category: "classroom",
    date: "2026-03-01",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-02.webp",
    alt: "Wisteria-and-foliage imagination corner at Blue Nest Borehamwood",
    aspectRatio: 0.75,
  },
  {
    id: "p-b8",
    type: "photo",
    title: "Calm baby room",
    description: "Soft, calm baby room with cot, book caddy and sensory mat.",
    branch: "borehamwood",
    category: "classroom",
    date: "2026-02-22",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-03.webp",
    alt: "Calm baby room with cot and sensory mat at Blue Nest Borehamwood",
    aspectRatio: 0.75,
  },
  {
    id: "p-b9",
    type: "photo",
    title: "Creation Station",
    description: "Art and creative-thinking station with easel and crayons.",
    branch: "borehamwood",
    category: "classroom",
    date: "2026-02-15",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-06.webp",
    alt: "Creation Station art area with chalkboard and crayon labels at Blue Nest Borehamwood",
    aspectRatio: 0.75,
  },
  {
    id: "p-b10",
    type: "photo",
    title: "Outdoor reading rug",
    description: "A quiet outdoor reading corner with picture books and soft toys.",
    branch: "borehamwood",
    category: "outdoor",
    date: "2026-02-10",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-07.webp",
    alt: "Outdoor reading rug with picture books and soft toys at Blue Nest Borehamwood",
    aspectRatio: 0.67,
  },
  {
    id: "p-b11",
    type: "photo",
    title: "Baby explorers",
    description: "A toddler exploring the wooden reading arch.",
    branch: "borehamwood",
    category: "learning",
    date: "2026-02-05",
    featured: false,
    source: "manual",
    isPublic: true,
    src: "/home/branches/borehamwood/borehamwood-gallery-10.webp",
    alt: "Baby exploring the wooden reading arch at Blue Nest Borehamwood",
    aspectRatio: 0.75,
  },

  // ── Videos ─────────────────────────────────────────────────────────────────
  {
    id: "v1",
    type: "video",
    title: "A day at Blue Nest Montessori",
    description: "Follow a typical day from morning arrival to afternoon exploration.",
    branch: "harrow",
    category: "classroom",
    date: "2026-04-01",
    featured: true,
    source: "youtube",
    isPublic: true,
    youtubeId: "ZRtdQ81jPUQ",
    thumbnailSrc: "/home/branches/harrow/harrow-gallery-01.webp",
    duration: "3:42",
  },
  {
    id: "v2",
    type: "video",
    title: "Our Forest School programme",
    description: "A look at how outdoor education shapes our youngest learners.",
    branch: "borehamwood",
    category: "outdoor",
    date: "2026-03-15",
    featured: false,
    source: "youtube",
    isPublic: true,
    youtubeId: "dQw4w9WgXcQ",
    thumbnailSrc: "/home/branches/borehamwood/borehamwood-hero.webp",
    duration: "4:18",
  },
  {
    id: "v3",
    type: "video",
    title: "Montessori materials explained",
    description: "Our lead educator walks through key Montessori learning tools.",
    branch: "pinner",
    category: "learning",
    date: "2026-02-20",
    featured: false,
    source: "youtube",
    isPublic: true,
    youtubeId: "3JZ_D3ELwOQ",
    thumbnailSrc: "/home/branches/pinner/pinner-gallery-03.webp",
    duration: "6:05",
  },

  // ── Updates ─────────────────────────────────────────────────────────────────
  {
    id: "u1",
    type: "update",
    title: "Spring term highlights from Harrow",
    description: "A round-up of our most memorable moments this spring term.",
    branch: "harrow",
    category: "events",
    date: "2026-04-14",
    featured: true,
    source: "manual",
    isPublic: true,
    excerpt:
      "This spring term has been full of discovery, creativity, and connection. From our garden planting project to the spring showcase, our children have been busy exploring the world around them.",
    href: "/blog",
  },
  {
    id: "u2",
    type: "update",
    title: "New outdoor equipment at Pinner",
    description: "We've upgraded our outdoor learning space with new adventure structures.",
    branch: "pinner",
    category: "outdoor",
    date: "2026-03-20",
    featured: false,
    source: "manual",
    isPublic: true,
    excerpt:
      "We are thrilled to unveil our newly upgraded outdoor area at Pinner. The new climbing frame, mud kitchen, and sensory garden have already become firm favourites with the children.",
    href: "/blog",
  },
  {
    id: "u3",
    type: "update",
    title: "Borehamwood earns Forest School Gold",
    description: "Our Borehamwood branch has been awarded the Forest School Gold accreditation.",
    branch: "borehamwood",
    category: "learning",
    date: "2026-03-05",
    featured: false,
    source: "manual",
    isPublic: true,
    excerpt:
      "We are incredibly proud to announce that Blue Nest Borehamwood has been awarded the Forest School Gold Award, recognising our commitment to nature-based learning and outdoor education.",
    href: "/blog",
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

// Branch colour tokens — matches the per-branch design tokens defined
// in styles/globals.css (--branch-* variables) so the gallery chips
// match the rest of the site.
export const BRANCH_COLOURS: Record<Exclude<BranchFilter, "all">, string> = {
  harrow:      "#E99FC1",  // rose
  pinner:      "#7ECFC8",  // teal
  borehamwood: "#BFD3A1",  // sage  (was the same teal as Pinner — fixed)
};

export const CATEGORY_LABELS: Record<Exclude<CategoryFilter, "all">, string> = {
  classroom: "Classroom",
  outdoor:   "Outdoor",
  events:    "Events",
  learning:  "Learning",
};
